@echo off
call Keanu.location.bat

echo Press any key When Done
echo KEANU SYSTEM ADDRESSES
echo ................................................................
echo ................................................................
echo ..  192.168.1.1    Router                                    ...
echo ..  192.168.1.100  Xpi                                       ...
echo ..  192.168.1.100  Xpi [\\192.168.1.100\share] SAMBA Files   ...
echo ..  192.168.1.105  Jey-PC                                    ...
echo ..  192.168.1.166  Xclient                                   ...
echo ..  192.168.1.168  Server68                                  ...
echo ..  192.168.1.169  LEGEND-T3                                 ...
echo ..  192.168.1.201  107_Fan                                   ...
echo ..  192.168.1.204  RM3                                       ...
echo ..  192.168.1.211  WLed1                                     ...
echo ..  192.168.1.212  WLed2                                     ...
echo ................................................................
echo ................................................................
echo KEANU : Those are The adresses
echo         What would you like me to do next?
:: if IsKeyDown(@SHIFT) then break

set /P c=What should I Do Next[Keanu/Exit]?
if /I "%c%" EQU "Keanu" goto :Keanu
if /I "%c%" EQU "Exit" goto :Exit


:Keanu
keanu.bat

:Exit
echo 
keanu.exit.bat 
